pipeline {
    agent any
    stages{
        
        stage('Git clone'){
            steps{
                git branch: 'main', url: 'https://github.com/Savitablore/docker-Java-kubernetes-project.git'
            }
        }
        stage('maven build'){        
            steps{
                dir('shopfront'){
                    sh 'mvn clean package -DskipTests'

                }
                
            }
        }
        stage('docker build'){
            steps{
            dir('shopfront'){
                sh 'sudo docker build -t java-project .'
            }
        }
        
        }
    }
}
